import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  try {
    const { simplifiedText, glossary, targetLanguage } = req.body;

    if (!simplifiedText) {
      return res.status(400).json({ message: 'Missing simplified text' });
    }

    const content = generateTextContent(simplifiedText, glossary || [], targetLanguage || 'en');
    
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="simplified-document.txt"');
    return res.status(200).send(content);
  } catch (error) {
    console.error('Download error:', error);
    return res.status(500).json({ message: 'Failed to generate download' });
  }
}

function generateTextContent(simplifiedText: string, glossary: Array<{term: string; definition: string}>, language: string): string {
  let content = '='.repeat(60) + '\n';
  content += '          SARALDOCS - SIMPLIFIED DOCUMENT\n';
  content += '='.repeat(60) + '\n\n';
  
  content += 'SIMPLIFIED VERSION:\n';
  content += '-'.repeat(40) + '\n\n';
  content += simplifiedText + '\n\n';
  
  if (glossary && glossary.length > 0) {
    content += '\n' + '='.repeat(60) + '\n';
    content += '                    GLOSSARY\n';
    content += '='.repeat(60) + '\n\n';
    
    glossary.forEach((item, index) => {
      content += `${index + 1}. ${item.term}\n`;
      content += `   ${item.definition}\n\n`;
    });
  }
  
  content += '\n' + '-'.repeat(60) + '\n';
  content += 'DISCLAIMER: This simplified version is for understanding\n';
  content += 'purposes only. Always refer to the original document for\n';
  content += 'official purposes.\n';
  content += '-'.repeat(60) + '\n';
  content += '\nGenerated by SaralDocs - Making Documents Simple\n';
  
  return content;
}
